
version: '3'

services:
  web1:
    build: .
    container_name: task-web1
    expose:
      - 5000
    volumes:
      - ./static:/static
    environment:
      - FLAG=krdu{pr1v3t_k4k_d3La}
    networks:
      ctfnet:
        ipv4_address: 10.0.0.51

networks:
  ctfnet:
    external: true