#define поболе >=
#define помене <=
#define боле >
#define мене <
#define аки ==
#define не !=
#define стане =
#define да +
#define дада ++
#define без -
#define раз *
#define дели /
#define нини ^
#define ъ ;
#define право true
#define бреше false
#define дулю 0
#define коли if( 
#define пущай ){
#define ежели }else if(
#define либо }else{
#define аминь }
#define покуда while(
#define твори do{
#define доколе }while(
#define буде );
#define откель for(
#define ступай goto
#define вон exit
#define цело int
#define дробно float
#define передробно double
#define азъ char
#define непотребо void
#define молви printf
#define поведай scanf
#define молитва int 
#define мольба void 
#define отченаш main(){
#define воздати return